services:
  - type: web
    name: anonymizer-backend
    env: python
    pythonVersion: 3.10.13
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
